// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webtestrevised.Data;

namespace webtestrevised.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20210611040214_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webtestrevised.Models.Client", b =>
                {
                    b.Property<string>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergency_Contact_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergency_Contact_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("l_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("login_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.HasIndex("StudentID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("webtestrevised.Models.CoursePaper", b =>
                {
                    b.Property<string>("CoursePaperID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CoursePaperID");

                    b.HasIndex("StaffID");

                    b.ToTable("CoursePapers");
                });

            modelBuilder.Entity("webtestrevised.Models.Login", b =>
                {
                    b.Property<string>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginID");

                    b.HasIndex("UserID");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("webtestrevised.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergency_Contact_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergency_Contact_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("l_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("login_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("webtestrevised.Models.Staff", b =>
                {
                    b.HasBaseType("webtestrevised.Models.User");

                    b.Property<string>("StaffNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("webtestrevised.Models.Student", b =>
                {
                    b.HasBaseType("webtestrevised.Models.User");

                    b.Property<DateTime>("membership_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("membership_Start")
                        .HasColumnType("datetime2");

                    b.Property<bool>("payment")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("webtestrevised.Models.Client", b =>
                {
                    b.HasOne("webtestrevised.Models.Student", "Student")
                        .WithMany("Clients")
                        .HasForeignKey("StudentID");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("webtestrevised.Models.CoursePaper", b =>
                {
                    b.HasOne("webtestrevised.Models.Staff", "Staff")
                        .WithMany("CoursePapers")
                        .HasForeignKey("StaffID");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("webtestrevised.Models.Login", b =>
                {
                    b.HasOne("webtestrevised.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webtestrevised.Models.Staff", b =>
                {
                    b.Navigation("CoursePapers");
                });

            modelBuilder.Entity("webtestrevised.Models.Student", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
